# Teste do endpoint raiz
GET http://127.0.0.1:5000/v1/users/test

###

# Teste do roteador
GET http://127.0.0.1:5000/v1/users/test

###

# Endpoint para registro de usuário
POST http://127.0.0.1:5000/v1/users/auth/register
Content-Type: application/json

{
    "username": "testuserTres",
    "email": "testTres@example.com",
    "cpf": "12345678900",
    "tutor": false,
    "adopter": false,
    "password": "minhasenha123"

}

###

# Endpoint para login de usuário
POST http://127.0.0.1:5000/v1/users/auth/login
Content-Type: application/json

{
    "username": "testuserTres",
    "password": "minhasenha123"
}

###

# Endpoint para buscar perfil do usuário
GET http://127.0.0.1:5000/v1/users/auth/profile?user_id=1